@echo off 

ECHO ----------------------
ECHO Killing Edge Process
ECHO ----------------------


TaskKill /im msedge.exe /f


SET APPLOCALDIR=C:%HOMEPATH%\AppData\Local


SET BRAVEUSERDIR=%APPLOCALDIR%\BraveSoftware\Brave-Browser\User Data\Default\

SET EDGEUSERDIR=%APPLOCALDIR%\Microsoft\Edge\User Data\Default\

SET CHROMEBOOKMARKFILES[0]=Bookmarks
SET CHROMEBOOKMARKFILES[1]=Bookmarks.bak

SET CHROMEFAVFILES[0]=Favicons
SET CHROMEFAVFILES[1]=Favicons-journal


SET CHROMEHISTORYFILES[0]=History
SET CHROMEHISTORYFILES[1]=History-journal

SET CHROMELDATAFILES[0]=Login Data
SET CHROMELDATAFILES[1]=Login Data-journal

ECHO ----------------------
ECHO ----------------------
ECHO ----------------------
ECHO Copying from Brave to Edge
ECHO ----------------------

del "%EDGEUSERDIR%%CHROMEBOOKMARKFILES[0]%.backup"
del "%EDGEUSERDIR%%CHROMEBOOKMARKFILES[1]%.backup"
rename "%EDGEUSERDIR%%CHROMEBOOKMARKFILES[0]%" "%CHROMEBOOKMARKFILES[0]%.backup"
rename "%EDGEUSERDIR%%CHROMEBOOKMARKFILES[1]%" "%CHROMEBOOKMARKFILES[1]%.backup"
copy "%BRAVEUSERDIR%%CHROMEBOOKMARKFILES[0]%" "%EDGEUSERDIR%"
copy "%BRAVEUSERDIR%%CHROMEBOOKMARKFILES[1]%" "%EDGEUSERDIR%"


del "%EDGEUSERDIR%%CHROMEHISTORYFILES[0]%.backup"
del "%EDGEUSERDIR%%CHROMEHISTORYFILES[1]%.backup"
rename "%EDGEUSERDIR%%CHROMEHISTORYFILES[0]%" "%CHROMEHISTORYFILES[0]%.backup"
rename "%EDGEUSERDIR%%CHROMEHISTORYFILES[1]%" "%CHROMEHISTORYFILES[1]%.backup"
copy "%BRAVEUSERDIR%%CHROMEHISTORYFILES[0]%" "%EDGEUSERDIR%"
copy "%BRAVEUSERDIR%%CHROMEHISTORYFILES[1]%" "%EDGEUSERDIR%"


del "%EDGEUSERDIR%%CHROMELDATAFILES[0]%.backup"
del "%EDGEUSERDIR%%CHROMELDATAFILES[1]%.backup"
rename "%EDGEUSERDIR%%CHROMELDATAFILES[0]%" "%CHROMELDATAFILES[0]%.backup"
rename "%EDGEUSERDIR%%CHROMELDATAFILES[1]%" "%CHROMELDATAFILES[1]%.backup"
copy "%BRAVEUSERDIR%%CHROMELDATAFILES[0]%" "%EDGEUSERDIR%"
copy "%BRAVEUSERDIR%%CHROMELDATAFILES[1]%" "%EDGEUSERDIR%"

ECHO ----------------------
ECHO ----------------------
ECHO Restarting Edge
ECHO ----------------------

start msedge --restore-last-session
